### ISSUE TITLE
Problems running kernel gateway in the docker

### ISSUE THREAD

**Issue by proofit404** [jupyter/kernel_gateway#209]
Hello guys,

I'm not a docker guru, so can any one explain to me the reason of behavior described below.

I run into a problem, when gateway unable to connect to the kernel it starts. An attempt to get kernel_info fails with timeout. But this bug occurs conditionally depending on how I start process inside docker.

If I use following docker setting it doesn't work

```yaml
version: '2'
  kernel:
    build:
      context: .
      dockerfile: compose/kernel
    volumes:
      - .:/code
    environment:
      PYTHONPATH: /code/.tox3.5.2/py35-django110/lib/python3.5/site-packages
    ports:
      - "8889:8889"
```

```dockerfile
FROM python:3.5
RUN pip install jupyter_kernel_gateway
RUN mkdir /code
WORKDIR /code
CMD ["jupyter", "kernelgateway", "--KernelGatewayApp.ip=0.0.0.0", "--KernelGatewayApp.port=8889"]
```

This also doesn't work

```yaml
version: '2'
  kernel:
    build:
      context: .
      dockerfile: compose/kernel
    command: jupyter kernelgateway --KernelGatewayApp.ip=0.0.0.0 --KernelGatewayApp.port=8889
    volumes:
      - .:/code
    environment:
      PYTHONPATH: /code/.tox3.5.2/py35-django110/lib/python3.5/site-packages
    ports:
      - "8889:8889"
```

```dockerfile
FROM python:3.5
RUN pip install jupyter_kernel_gateway
RUN mkdir /code
WORKDIR /code
```

But this configuration works and gateway successfully connect to the started kernels

```yaml
version: '2'
  kernel:
    build:
      context: .
      dockerfile: compose/kernel
    volumes:
      - .:/code
    environment:
      PYTHONPATH: /code/.tox3.5.2/py35-django110/lib/python3.5/site-packages
    ports:
      - "8889:8889"
```

```dockerfile
FROM python:3.5
RUN pip install jupyter_kernel_gateway
RUN mkdir /code
WORKDIR /code
CMD jupyter kernelgateway --KernelGatewayApp.ip=0.0.0.0 --KernelGatewayApp.port=8889
```

Can any one explain to me whats going on? Why shell format of writing cmd works and exec format doesn't? I spent whole day trying to make this thing work, maybe this should be explained in the wiki somehow?
